### ISSUE TITLE
some other crash (very rare)

### ISSUE THREAD

**Issue by rvencu** [Wikidepia/crawlingathome-worker#7]
Got this today
```
Traceback (most recent call last):
  File "crawlingathome.py", line 503, in <module>
    zip_ref.extractall("./")
  File "crawlingathome.py", line 185, in df_clipfilter
  File "/home/rvencu/gpu/crawlingathome-worker/clip_filter.py", line 51, in preprocess_images
    im_dataset = datasets.Dataset.from_pandas(df)
  File "/home/rvencu/.local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1619, in map
    return self._map_single(
  File "/home/rvencu/.local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 186, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/rvencu/.local/lib/python3.8/site-packages/datasets/fingerprint.py", line 397, in wrapper
    out = func(self, *args, **kwargs)
  File "/home/rvencu/.local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1959, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/home/rvencu/.local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1855, in apply_function_on_filtered_inputs
    function(*fn_args, effective_indices, **fn_kwargs) if with_indices else function(*fn_args, **fn_kwargs)
  File "/home/rvencu/gpu/crawlingathome-worker/clip_filter.py", line 27, in similarity_imgalt
    max_texts = [text[:77] for text in batch["TEXT"]]
  File "/home/rvencu/.local/lib/python3.8/site-packages/clip/clip.py", line 190, in tokenize
    raise RuntimeError(f"Input {texts[i]} is too long for context length {context_length}")
RuntimeError: Input �}���� �悭�킩��ŐVWindowsXP�A�[�L�e�N�`���̊�{�Ǝd�g�݁\�V����f�W�^���v���b�g�t�H�[ is too long for context length 77
```

**Comment by rvencu** [comment]
58%|█████████████████████████████████████████████████████                                      | 7/12 [00:13<00:09,  1.89s/ba]
Traceback (most recent call last):
  File "crawlingathome.py", line 518, in <module>
    # recreate parsed dataset and run CLIP filtering
  File "crawlingathome.py", line 187, in df_clipfilter
    img_embedding, similarities = clip.preprocess_images(df)
  File "/home/rvencu/gpu/crawlingathome-worker/clip_filter.py", line 52, in preprocess_images
    im_dataset = im_dataset.map(self.similarity_imgalt, batched=True, batch_size=1024)
  File "/home/rvencu/.local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1619, in map
    return self._map_single(
  File "/home/rvencu/.local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 186, in wrapper
    out: Union["Dataset", "DatasetDict"] = func(self, *args, **kwargs)
  File "/home/rvencu/.local/lib/python3.8/site-packages/datasets/fingerprint.py", line 397, in wrapper
    out = func(self, *args, **kwargs)
  File "/home/rvencu/.local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1959, in _map_single
    batch = apply_function_on_filtered_inputs(
  File "/home/rvencu/.local/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1855, in apply_function_on_filtered_inputs
    function(*fn_args, effective_indices, **fn_kwargs) if with_indices else function(*fn_args, **fn_kwargs)
  File "/home/rvencu/gpu/crawlingathome-worker/clip_filter.py", line 28, in similarity_imgalt
    texts = clip.tokenize(max_texts).to(device)
  File "/home/rvencu/.local/lib/python3.8/site-packages/clip/clip.py", line 190, in tokenize
    raise RuntimeError(f"Input {texts[i]} is too long for context length {context_length}")
RuntimeError: Input (◡‿◡✿) (◕‿◕✿) CHRISTMAS DREAMS (◡‿◡✿) (◕‿◕✿) by ╰⊰✿ℒᵒᶹᵉ Bonita✿⊱╮ Lalonde✿⊱╮ is too long for context length 77

**Comment by Wikidepia** [comment]
Thanks, I will take a look today

**Comment by rvencu** [comment]
I also saved the data in case you need for testing
